notifications:
  email: false

env:
  - NODE_ENV=ci

language: node_js

before_install:
  - openssl aes-256-cbc -K $encrypted_645dc410e90f_key -iv $encrypted_645dc410e90f_iv -in .env.staging.local.enc -out .env.staging.local -d

install:
  - npm install

node_js:
  - '8'

script:
  - npm test

deploy:
  - provider: script
    script: npm run deploy:staging -- --token \"$FIREBASE_TOKEN\"
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: npm run deploy:production -- --token \"$FIREBASE_TOKEN\"
    skip_cleanup: true
    on:
      tags: true
      branch: master
