notifications:
  email: false

language: node_js

preinstall:
  - npm i -g npm

install:
  - npm install

node_js:
  - "8"

script:
  - npm test

before_deploy:
  - npm run build

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: ASjeeINmG6YBqWhjFRVH5tD/pZBRdzkMdA7tBE2KEqrJfbf6JGdo3VHSqKiegEMxVJUvApzxXy2u0Z47CUrjBcn/VbG3d/RsRPiFKB8FYqY6w2IwI0e7MSpQwlxMIoSLtPUmoWXFpUys3CBbGjeqQjLn9bkokAFLZ46qH1lnFWzI1uF83INhMgN6qTuWibYXrYabp54mCgLmkb3ZdRONnxt1gjvGEGRfjUXjpalBbOFHMIBbLtTt307ZVN8DVufFp4EnxrEp+XaaA3MKhuDfXphUOzfsjGCOmfB3kq+fI0QVUwMgRCFwWXDI0Xliu9DLnqFjPxqNqxaY01CuflfLM8EwA49bE2yjqjAQHlAcRHbW3GpZ6bt33ucdphxLtMIu4WTuPdVZddsXHK5ANSpvi6bKq7tgYoZFkcTqmSK0EgloruA0me6nv5NsiXZi4iInWrD+eMfMzMS9SFHhrTd/ALXc/BfbLGP4HO718iXcYCP7ZasWavyY2uOdWWQyBe9nusjNzPwDsNabgGEXeJ6RnoFMMTH860WhWVr82eGI24LvokqdwBOCVSThSgEQQs9ojwQzPHhVdunflKTCz/emUrUmrlBSkSoETztmIFEb4KlCS4BU/7f9aJRl0pl5gHoewrfiwXvCr2uXhOvup+HWdlTZLDU0tOte87OMORTV/58=
  project: "mjcalc-staging"
  on:
    repo: ycmjason/mjcalc
    branch: master
